# Generated by Django 3.2.5 on 2021-09-08 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BEDS_Mapping',
            fields=[
                ('beds_code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name_desc', models.CharField(max_length=200)),
                ('nrc_code', models.SmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Math_Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField()),
                ('grade', models.SmallIntegerField()),
                ('total_tested', models.IntegerField()),
                ('L1_count', models.IntegerField()),
                ('L1_percent', models.SmallIntegerField()),
                ('L2_count', models.IntegerField()),
                ('L2_percent', models.SmallIntegerField()),
                ('L3_count', models.IntegerField()),
                ('L3_percent', models.SmallIntegerField()),
                ('L4_count', models.IntegerField()),
                ('L4_percent', models.SmallIntegerField()),
                ('mean_score', models.SmallIntegerField(blank=True, null=True)),
                ('beds_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nyed.beds_mapping')),
            ],
        ),
        migrations.CreateModel(
            name='ELA_Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField()),
                ('grade', models.SmallIntegerField()),
                ('total_tested', models.IntegerField()),
                ('L1_count', models.IntegerField()),
                ('L1_percent', models.SmallIntegerField()),
                ('L2_count', models.IntegerField()),
                ('L2_percent', models.SmallIntegerField()),
                ('L3_count', models.IntegerField()),
                ('L3_percent', models.SmallIntegerField()),
                ('L4_count', models.IntegerField()),
                ('L4_percent', models.SmallIntegerField()),
                ('mean_score', models.SmallIntegerField(blank=True, null=True)),
                ('beds_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nyed.beds_mapping')),
            ],
        ),
        migrations.CreateModel(
            name='Correlation_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField()),
                ('g1to6_class_size', models.SmallIntegerField()),
                ('ela_g3to6_L1_percent', models.SmallIntegerField(blank=True, null=True)),
                ('math_g3to6_L1_percent', models.SmallIntegerField(blank=True, null=True)),
                ('per_free_lunch', models.SmallIntegerField(blank=True, null=True)),
                ('per_reduced_lunch', models.SmallIntegerField(blank=True, null=True)),
                ('beds_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nyed.beds_mapping')),
            ],
        ),
        migrations.AddIndex(
            model_name='math_result',
            index=models.Index(fields=['beds_code', 'year', 'grade'], name='nyed_math_r_beds_co_74fb44_idx'),
        ),
        migrations.AddIndex(
            model_name='ela_result',
            index=models.Index(fields=['beds_code', 'year', 'grade'], name='nyed_ela_re_beds_co_c5705f_idx'),
        ),
        migrations.AddIndex(
            model_name='correlation_data',
            index=models.Index(fields=['beds_code', 'year'], name='nyed_correl_beds_co_26cf71_idx'),
        ),
    ]
